spring:
  application:
    name: processarelatoriodesif-api
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@compliance-db-prd.cfv6ktavqllz.sa-east-1.rds.amazonaws.com:1521/CSFPRD}
    username: ${SPRING_DATASOURCE_USERNAME:csf_own}
    password: ${SPRING_DATASOURCE_PASSWORD:Jfg#n76s3dvC4Az}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    cache:
      connection:
        mode: connection

  mail:
    host: smtp.gmail.com
    port: 25 # 587 With SSL # 25 (Without TLS/SSL)
    username: ${mail.user}
    password: ${mail.password}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true
server:
  port: ${portProcessaRel}

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka_zone}:${eureka_port}/eureka
