spring:
  application:
    name: stjwttoken

  data:
    mongodb:
      database: st-boot-jwt
      host: ${MONGO_DB_HOST} 
      password: Y3N0LWJvb3Qtand0LTIwWFgjI0A=
      username: st-boot-jwt-20XX

server:
  port: 8080
    
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE}:8761/eureka

#db.createUser({user:"st-boot-jwt-20XX",pwd:"Y3N0LWJvb3Qtand0LTIwWFgjI0A=", roles: [{ role: "readWrite", db: "st-boot-jwt" }], passwordDigestor:"server"});