package br.com.cadastroit.services.api.domain;

public enum ParametroChaveType {


	CONFIGURACAO_ARREDONDAMENTO(Type.STRING),
	TIPO_ARREDONDAMENTO(Type.STRING),
	REGRA_ARREDONDAMENTO(Type.STRING),
	DECIMAIS_CONFIGURAVEIS(Type.STRING),
	CONFIGURACAO_CALCULO_DESCONTO_ITEM(Type.STRING),
	VALOR_MINIMO_CHEQUE(Type.NUMBER),
	RPS_QUANTIDADE_DIAS_VENCIMENTO_ALERTA(Type.INTEGER),
	BLOQUEIO_EDICAO_PRODUTO_INTEGRADO(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_MIN_MAX(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_FORN(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_CLAS_FISC_CONT(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_PRECO_CUSTO(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_PRECO_VENDA(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_DESC_MAX(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_COMISSAO(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_TRIBUTACAO_NIVEL(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_NOME_TRIBUTACAO_NIVEL(Type.STRING),
	BLOQUEIO_EDICAO_NIVEL_CATEGORIA(Type.BOOLEAN),
	BLOQUEIO_EDICAO_FORNECEDOR_INTEGRADO(Type.BOOLEAN),
	BLOQUEIO_EDICAO_CATEGORIA_INTEGRADA(Type.BOOLEAN),
	BLOQUEIO_EDICAO_GERACAO_CODIGO(Type.BOOLEAN),
	CARTAO_QTDE_MAXIMA_PARCELAS(Type.INTEGER),
	IMAGEM_LOGO_EMPRESA(Type.FILE),
	GESTAO_FRANQUIA_ROYALTY_RECEBER_CONTA_DEBITO(Type.NUMBER),
	GESTAO_FRANQUIA_ROYALTY_RECEBER_CONTA_CREDITO(Type.NUMBER),
	GESTAO_FRANQUIA_ROYALTY_RECEBER_CONTA_CREDITO_REPASSE(Type.NUMBER),
	GESTAO_FRANQUIA_ROYALTY_PAGAR_CONTA_DEBITO(Type.NUMBER),
	GESTAO_FRANQUIA_ROYALTY_PAGAR_CONTA_CREDITO(Type.NUMBER),
	GESTAO_FRANQUIA_FUNDOMKT_RECEBER_CONTA_DEBITO(Type.NUMBER),
	GESTAO_FRANQUIA_FUNDOMKT_RECEBER_CONTA_CREDITO(Type.NUMBER),
	GESTAO_FRANQUIA_FUNDOMKT_RECEBER_CONTA_CREDITO_REPASSE(Type.NUMBER),
	GESTAO_FRANQUIA_FUNDOMKT_PAGAR_CONTA_DEBITO(Type.NUMBER),
	GESTAO_FRANQUIA_FUNDOMKT_PAGAR_CONTA_CREDITO(Type.NUMBER),

	FLUXO_APROVACAO_PEDIDO_COMPRA(Type.BOOLEAN),

	PEDIDO_COMPRA_VALIDA_REFERENCIA_FORNECEDOR(Type.BOOLEAN),
	PEDIDO_COMPRA_VALIDA_REFERENCIA_FORNECEDOR_POR_ENTIDADE(Type.BOOLEAN),
	PEDIDO_COMPRA_VALIDA_REFERENCIA_FORNECEDOR_POR_FORNECEDOR(Type.BOOLEAN),
	PEDIDO_COMPRA_VALIDA_REFERENCIA_FORNECEDOR_POR_VALORTOTAL(Type.BOOLEAN),
	PEDIDO_COMPRA_VALIDA_REFERENCIA_FORNECEDOR_IGNORAR_CANCELADOS(Type.BOOLEAN),

	ICMS_DIFAL_ORIGEM_CONTA_DEBITO(Type.NUMBER),
	ICMS_DIFAL_ORIGEM_CONTA_CREDITO(Type.NUMBER),
	ICMS_DIFAL_DESTINO_CONTA_DEBITO(Type.NUMBER),
	ICMS_DIFAL_DESTINO_CONTA_CREDITO(Type.NUMBER),
	FUNDO_POBREZA_CONTA_DEBITO(Type.NUMBER),
	FUNDO_POBREZA_CONTA_CREDITO(Type.NUMBER),

	BLOQUEIO_CADASTRO_PRODUTO(Type.BOOLEAN),

	RECEBIMENTO_TRANSFERENCIA_EXTERNA_CONTA_CREDITO(Type.NUMBER),
	RECEBIMENTO_TRANSFERENCIA_EXTERNA_CONTA_DEBITO(Type.NUMBER),
	CONTROLE_ATENDIMENTO(Type.BOOLEAN),

	EMISSAO_NOTAFISCAL_DEVOLUCAOVENDA_AUTOMATICA(Type.BOOLEAN),

	USA_INCREMENTO_COD_PROD(Type.BOOLEAN),
	INCREMENTO_FORMATADO_COD_PROD(Type.BOOLEAN),
	USA_SEPARADOR_COD_PROD(Type.BOOLEAN),

	OBSERVACAO_PADRAO_PC(Type.STRING),

	SMTP_HOST(Type.STRING),
	SMTP_PORT(Type.STRING),
	SMTP_USER(Type.STRING),
	SMTP_PASS(Type.STRING),

	EMAIL_REMETENTE_PC(Type.STRING),
	ATUALIZA_STATUS_CREDIARIO(Type.BOOLEAN),
	CONTRATO_CREDIARIO(Type.STRING),


	BLOQUEIO_EDICAO_SERVICO_INTEGRADO(Type.BOOLEAN),

	CODIGO_IMPRESSAO_PDV(Type.STRING),

	BLOQUEIO_CADASTRO_SERVICO(Type.BOOLEAN),

	PERMITE_PESQUISA_CLIENTE_REDE_PDV(Type.BOOLEAN),


	PEDIDOVENDA_SIMPLESFATURAMENTO_CONTACREDITO(Type.NUMBER),

	PROGRAMA_FIDELIDADE(Type.STRING),
	PROGRAMA_FIDELIDADE_AUTHORIZATION(Type.STRING),
	PROGRAMA_FIDELIDADE_TOKEN(Type.STRING),
	PROGRAMA_FIDELIDADE_LOGIN(Type.STRING),
	PROGRAMA_FIDELIDADE_LOJA_ID(Type.NUMBER),
	PROGRAMA_FIDELIDADE_CODIGO_EMPRESA(Type.STRING),
	// Percentual máximo de valor sobre o total a pagar da venda
	PROGRAMA_FIDELIDADE_PERCENTUAL_MAXIMO_USO_VENDA(Type.NUMBER),
	// Bloqueia uso do programa fidelidade quando existir ações promocionais, vouchers ou tabelas de preços
	PROGRAMA_FIDELIDADE_BLOQUEIO_COM_ACAO_PROMOCIONAL(Type.BOOLEAN),
	PROGRAMA_FIDELIDADE_BLOQUEIO_COM_VOUCHER(Type.BOOLEAN),
	PROGRAMA_FIDELIDADE_BLOQUEIO_COM_TABELA_PROMOCIONAL(Type.BOOLEAN),

	PERMITE_PRODUTO_NOME_DUPLICADO(Type.BOOLEAN),
	USA_CODIGO_VALOR_ATRIBUTO_NOME_PRODUTO(Type.BOOLEAN),

	/**
	 * @deprecated Parâmetro descontinuado: utilizar ENTRADANOTA_ALTERARVALORPROVISAO pois é por entidade
	 */
	ENTRADANOTA_PERMITEALTERARVALORPROVISAO(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_BENEFICIO_FISCAL(Type.BOOLEAN),

	VISAO_VENDEDOR(Type.STRING),
	MODO_VISUALIZACAO_VENDEDOR(Type.STRING),

	VISAO_GERENTE(Type.STRING),
	MODO_VISUALIZACAO_GERENTE(Type.STRING),

	VISAO_SUPERVISOR(Type.BOOLEAN),

	COMPRA_SEMINOVO_CONTACUSTO(Type.NUMBER),

	PACOTE_SERVICOS_ADIANTAMENTO_CONTACREDITO(Type.NUMBER),

	RESTRINGIR_RESULTADOS_VOMOBILE(Type.BOOLEAN),

	TERCEIRO_CONTROLE_TEMPO_LABEL(Type.STRING),
	TERCEIRO_CONTROLE_TEMPO_TIPO_CONTAGEM(Type.STRING),

	/* Permite inclusão de serviços à provisão e consequentemente a criação de RPS após sua criação */
	RPS_NA_PROVISAO(Type.BOOLEAN),

	ENTRADANOTA_UTILIZACONFERENCIAPRODUTO(Type.BOOLEAN),
	ENTRADANOTA_GERAPROVISAONAOAUTORIZADA(Type.BOOLEAN),
	ENTRADANOTA_ALTERARVALORPROVISAO(Type.BOOLEAN),
	ENTRADANOTA_OPERACAOCONFERENCIAPRODUTO(Type.NUMBER),

	PAGAMENTO_ESCRITURAL(Type.BOOLEAN),

	API_INTEGRADOR_TOKEN(Type.STRING),

	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_DISPONIVEL_ECOMMERCE(Type.BOOLEAN),
	LIBERACAO_EDICAO_PRODUTO_INTEGRADO_DISPONIVEL_MARKETPLACE(Type.BOOLEAN),

	CONFIGURACAO_VENDEDOR_CADASTRO_CLIENTE_AUTORIZACAO_GERENTE(Type.BOOLEAN),

	ORDEM_PRODUCAO_CONTA_CUSTO(Type.NUMBER),

	PERMITE_TROCA_NACIONAL(Type.BOOLEAN),
	PERMITE_DEVOLUCAO_DINHEIRO(Type.BOOLEAN),
	DEVOLUCAO_SANGRIA_CONTA_DEBITO_CREDITO(Type.NUMBER),
	CONFIGURACAO_AUTORIZACAO_GERENTE_TROCA_NACIONAL(Type.BOOLEAN),
	EMISSAO_NOTAFISCAL_TROCA_NACIONAL_AUTOMATICA(Type.BOOLEAN),
	DEVOLUCAO_VENDA_BAIXA_CONTABIL_PROVISAO_CONTA_CREDITO(Type.NUMBER),

	ENVIAR_NOME_SIMPLIFICADO(Type.BOOLEAN),

	RENEGOCIACAO_MANTER_CONTAS_PROVISAO(Type.BOOLEAN),
	RENEGOCIACAO_CONTACREDITO(Type.NUMBER),
	RENEGOCIACAO_CONTADEBITO(Type.NUMBER),

	TROCA_NACIONAL_CONTA_DEBITO(Type.NUMBER),

	VOUCHER_VENDAS_CONTA_DEBITO(Type.NUMBER),
	VOUCHER_VALE_PRESENTE_VENDAS_CONTA_DEBITO(Type.NUMBER),

	SEPARAR_CARTAO_TEF_E_MANUAL(Type.BOOLEAN),

	CARTAO_VALOR_MINIMO_PARCELAS(Type.NUMBER),
	OPERACAO_VENDA_PRODUTOS_PDV(Type.NUMBER),

	HABILITAR_LINK_RELATORIO_COBRANCA(Type.BOOLEAN),
	LINK_RELATORIO_COBRANCA(Type.STRING),

	COMPOSICAO_NOME_PRODUTO_IGNORAR_CODIGO(Type.STRING),
	UTILIZA_COMPOSICAO_NOME_PRODUTO(Type.BOOLEAN),

	UTILIZA_CHAT_VAREJONLINE(Type.BOOLEAN),

	BOLETO_BANCARIO_ASSUNTO_EMAIL(Type.STRING),
	BOLETO_BANCARIO_MENSAGEM_INTRODUCAO_EMAIL(Type.STRING),
	BOLETO_BANCARIO_CORPO_EMAIL(Type.STRING),
	BOLETO_BANCARIO_MENSAGEM_AUTOMATICA_EMAIL(Type.STRING),
	BOLETO_BANCARIO_MENSAGEM_NOTIFICACAO_EMAIL(Type.STRING),

	FUNDO_POBREZA_ST_CONTA_DEBITO(Type.NUMBER),
	FUNDO_POBREZA_ST_CONTA_CREDITO(Type.NUMBER),

	RPS_GERAR_ROYALTIES_PROVISAO_AUTOMATICAMENTE(Type.BOOLEAN),
	RPS_SERVICO_ROYALTIES_PROVISAO(Type.NUMBER),

	ENTIDADE_MOVIMENTA_PRODUTO_EPC(Type.BOOLEAN),

	ENTRADANOTA_SUGERE_VINCULO_AUTOMATICO_XML_CUSTO_PRODUTO_PEDIDO_COMPRA(Type.BOOLEAN),
	ENTRADANOTA_PERMITE_VINCULAR_ENTIDADE_DIFERENTE_PEDIDO_COMPRA(Type.BOOLEAN),

	LINK_PAGAMENTO_BELVO(Type.BOOLEAN),

	PERMITIR_TROCA_APENAS_MESMA_EMPRESA(Type.BOOLEAN),

	CONFIGURACAO_DESCONTO_CLASSE_TERCEIRO(Type.STRING),
	CONFIGURACAO_DESCONTO_TABELA_PRECO(Type.STRING),
	CONFIGURACAO_DESCONTO_DESCONTO_PROGRESSIVO(Type.STRING),
	CONFIGURACAO_DESCONTO_DESCONTO_MANUAL(Type.STRING),

	DESCONTO_NO_TOTAL_CONSIDERA_DESCONTO_MAXIMO_ITEM(Type.BOOLEAN),

	URL_INTEGRACAO_APIPASS(Type.STRING),

	ENVIAR_EMAILNF_ECOMMERCE(Type.BOOLEAN),
	ENVIAR_EMAILNF_MARKETPLACE(Type.BOOLEAN),
	ENVIAR_EMAILNF_LOJAFISICA(Type.BOOLEAN),

	PERMITIR_ATIVAR_ACAO_PROMOCIONAL_ITENS_UTILIZADOS_OUTRAS_ACOES(Type.BOOLEAN),
	PERMITIR_ACUMULAR_DESCONTO_PRODUTO_ACAO_PROMOCIONAL(Type.BOOLEAN),

	HABILITAR_VALIDADE_VALE_TROCA(Type.BOOLEAN),
	DIAS_VALIDADE_VALE_TROCA(Type.INTEGER),
	CONTA_BAIXA_VALE_TROCA(Type.NUMBER),
	SCHEDULER_UUID_BAIXA_VALE_TROCA(Type.STRING),

	PDV_EXIBIR_FOTOS_PRODUTOS(Type.BOOLEAN),
	PERMITIR_MESMO_CODIGO_INTERNO_PRODUTO(Type.BOOLEAN),

	FIDELIDADE_GERACAO_BONUS_TIPO_PAGAMENTO(Type.STRING),
	FIDELIDADE_NAO_PERMITIR_CONSUMO_BONUS_TIPO(Type.STRING),
	FIDELIDADE_NAO_PERMITIR_CONSUMO_BONUS_TIPO_REGRA(Type.STRING),

	SOLICITACAO_PAGAMENTO_REQUER_APROVACAO_DIRETORIA(Type.BOOLEAN),
	SOLICITACAO_PAGAMENTO_USUARIO_DIRETORIA_APROVACAO(Type.INTEGER),
	SOLICITACAO_PAGAMENTO_VALOR_ALCADA_DIRETORIA(Type.NUMBER),

	ENVIAR_VALE_PRESENTE_NOTA_FISCAL(Type.BOOLEAN),

	MOTIVO_DEVOLUCAO_SUGESTAO_PADRAO(Type.STRING),

	ENTIDADE_CAPACIDADE_MAXIMA_ESTOQUE(Type.NUMBER),

	CONSULTA_ESTOQUE_ENTIDADE_PDV(Type.STRING),

	UTILIZA_FLUXO_ALTERAR_REGRA_CONTRATO(Type.BOOLEAN),
	EXCLUI_CATEGORIA_SERVICO_APURACAO(Type.BOOLEAN),
	EXCLUI_CATEGORIA_SERVICO_APURACAO_IDS(Type.NUMBER),

	BLOQUEAR_EMISSAO_NOTA_NUMERO_VALE_PRESENTE(Type.BOOLEAN),
	BLOQUEAR_EMISSAO_NOTA_NUMERO_VALE_PRESENTE_NUMERO(Type.STRING),

	VALE_PRESENTE_TAMANHO_MINIMO(Type.BOOLEAN),
	VALE_PRESENTE_TAMANHO_MINIMO_TIPO(Type.STRING),
	VALE_PRESENTE_TAMANHO_MINIMO_TAMANHO(Type.INTEGER),
	VALE_PRESENTE_TAMANHO_MINIMO_TAMANHO_MAXIMO(Type.INTEGER),

	CONFIGURACAO_CONFERENCIA_ITENS_ANTES_DE_FINALIZAR_VENDA(Type.BOOLEAN);

	private Type tipo;

	private ParametroChaveType(Type tipo) {

		this.tipo = tipo;
	}

	public Type getTipo() {

		return tipo;
	}

	public String getTipoDiscriminator() {

		return getTipo().discriminator;
	}

	public enum Type {

		STRING("S"),
		BOOLEAN("B"),
		NUMBER("N"),
		INTEGER("I"),
		FILE("F"),;

		private String discriminator;

		private Type(String discriminator) {

			setDiscriminator(discriminator);
		}

		public String getDiscriminator() {

			return discriminator;
		}

		public void setDiscriminator(String discriminator) {

			this.discriminator = discriminator;
		}

	}

}
